//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratorService.JavaServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://facade.bank.com/", ConfigurationName="JavaServer.Generator")]
    public interface Generator {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://facade.bank.com/Generator/ServiceOperationRequest", ReplyAction="http://facade.bank.com/Generator/ServiceOperationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceOperation))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GeneratorService.JavaServer.ServiceOperationResponse1 ServiceOperation(GeneratorService.JavaServer.ServiceOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://facade.bank.com/Generator/ServiceOperationRequest", ReplyAction="http://facade.bank.com/Generator/ServiceOperationResponse")]
        System.Threading.Tasks.Task<GeneratorService.JavaServer.ServiceOperationResponse1> ServiceOperationAsync(GeneratorService.JavaServer.ServiceOperationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facade.bank.com/")]
    public partial class ServiceOperationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facade.bank.com/")]
    public partial class ServiceOperation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string arg0Field;
        
        private object[] arg1Field;
        
        private string arg2Field;
        
        private int arg3Field;
        
        private int arg4Field;
        
        private string arg5Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("arg1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public object[] arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
                this.RaisePropertyChanged("arg1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string arg2 {
            get {
                return this.arg2Field;
            }
            set {
                this.arg2Field = value;
                this.RaisePropertyChanged("arg2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int arg3 {
            get {
                return this.arg3Field;
            }
            set {
                this.arg3Field = value;
                this.RaisePropertyChanged("arg3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int arg4 {
            get {
                return this.arg4Field;
            }
            set {
                this.arg4Field = value;
                this.RaisePropertyChanged("arg4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string arg5 {
            get {
                return this.arg5Field;
            }
            set {
                this.arg5Field = value;
                this.RaisePropertyChanged("arg5");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ServiceOperation", WrapperNamespace="http://facade.bank.com/", IsWrapped=true)]
    public partial class ServiceOperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facade.bank.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facade.bank.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("arg1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public object[] arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facade.bank.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facade.bank.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facade.bank.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facade.bank.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg5;
        
        public ServiceOperationRequest() {
        }
        
        public ServiceOperationRequest(string arg0, object[] arg1, string arg2, int arg3, int arg4, string arg5) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ServiceOperationResponse", WrapperNamespace="http://facade.bank.com/", IsWrapped=true)]
    public partial class ServiceOperationResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facade.bank.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public ServiceOperationResponse1() {
        }
        
        public ServiceOperationResponse1(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GeneratorChannel : GeneratorService.JavaServer.Generator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GeneratorClient : System.ServiceModel.ClientBase<GeneratorService.JavaServer.Generator>, GeneratorService.JavaServer.Generator {
        
        public GeneratorClient() {
        }
        
        public GeneratorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GeneratorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneratorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneratorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GeneratorService.JavaServer.ServiceOperationResponse1 GeneratorService.JavaServer.Generator.ServiceOperation(GeneratorService.JavaServer.ServiceOperationRequest request) {
            return base.Channel.ServiceOperation(request);
        }
        
        public bool ServiceOperation(string arg0, object[] arg1, string arg2, int arg3, int arg4, string arg5) {
            GeneratorService.JavaServer.ServiceOperationRequest inValue = new GeneratorService.JavaServer.ServiceOperationRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            GeneratorService.JavaServer.ServiceOperationResponse1 retVal = ((GeneratorService.JavaServer.Generator)(this)).ServiceOperation(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GeneratorService.JavaServer.ServiceOperationResponse1> GeneratorService.JavaServer.Generator.ServiceOperationAsync(GeneratorService.JavaServer.ServiceOperationRequest request) {
            return base.Channel.ServiceOperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<GeneratorService.JavaServer.ServiceOperationResponse1> ServiceOperationAsync(string arg0, object[] arg1, string arg2, int arg3, int arg4, string arg5) {
            GeneratorService.JavaServer.ServiceOperationRequest inValue = new GeneratorService.JavaServer.ServiceOperationRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            return ((GeneratorService.JavaServer.Generator)(this)).ServiceOperationAsync(inValue);
        }
    }
}
