//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratorService.JavaServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://facade.bank.com/", ConfigurationName="JavaServer.Generator")]
    public interface Generator {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://facade.bank.com/Generator/ServiceOperationRequest", ReplyAction="http://facade.bank.com/Generator/ServiceOperationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceOperationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceOperation))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GeneratorService.JavaServer.ServiceOperationResponse1 ServiceOperation(GeneratorService.JavaServer.ServiceOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://facade.bank.com/Generator/ServiceOperationRequest", ReplyAction="http://facade.bank.com/Generator/ServiceOperationResponse")]
        System.Threading.Tasks.Task<GeneratorService.JavaServer.ServiceOperationResponse1> ServiceOperationAsync(GeneratorService.JavaServer.ServiceOperationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facade.bank.com/")]
    public partial class ServiceOperationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facade.bank.com/")]
    public partial class ServiceOperation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apptokenField;
        
        private object[] dataField;
        
        private string infoField;
        
        private int operationsField;
        
        private int statusField;
        
        private string usertokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apptoken {
            get {
                return this.apptokenField;
            }
            set {
                this.apptokenField = value;
                this.RaisePropertyChanged("apptoken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public object[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
                this.RaisePropertyChanged("info");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int operations {
            get {
                return this.operationsField;
            }
            set {
                this.operationsField = value;
                this.RaisePropertyChanged("operations");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string usertoken {
            get {
                return this.usertokenField;
            }
            set {
                this.usertokenField = value;
                this.RaisePropertyChanged("usertoken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ServiceOperation", WrapperNamespace="http://facade.bank.com/", IsWrapped=true)]
    public partial class ServiceOperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facade.bank.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apptoken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facade.bank.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public object[] data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facade.bank.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string info;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facade.bank.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int operations;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facade.bank.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facade.bank.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usertoken;
        
        public ServiceOperationRequest() {
        }
        
        public ServiceOperationRequest(string apptoken, object[] data, string info, int operations, int status, string usertoken) {
            this.apptoken = apptoken;
            this.data = data;
            this.info = info;
            this.operations = operations;
            this.status = status;
            this.usertoken = usertoken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ServiceOperationResponse", WrapperNamespace="http://facade.bank.com/", IsWrapped=true)]
    public partial class ServiceOperationResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://facade.bank.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public ServiceOperationResponse1() {
        }
        
        public ServiceOperationResponse1(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GeneratorChannel : GeneratorService.JavaServer.Generator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GeneratorClient : System.ServiceModel.ClientBase<GeneratorService.JavaServer.Generator>, GeneratorService.JavaServer.Generator {
        
        public GeneratorClient() {
        }
        
        public GeneratorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GeneratorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneratorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneratorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GeneratorService.JavaServer.ServiceOperationResponse1 GeneratorService.JavaServer.Generator.ServiceOperation(GeneratorService.JavaServer.ServiceOperationRequest request) {
            return base.Channel.ServiceOperation(request);
        }
        
        public bool ServiceOperation(string apptoken, object[] data, string info, int operations, int status, string usertoken) {
            GeneratorService.JavaServer.ServiceOperationRequest inValue = new GeneratorService.JavaServer.ServiceOperationRequest();
            inValue.apptoken = apptoken;
            inValue.data = data;
            inValue.info = info;
            inValue.operations = operations;
            inValue.status = status;
            inValue.usertoken = usertoken;
            GeneratorService.JavaServer.ServiceOperationResponse1 retVal = ((GeneratorService.JavaServer.Generator)(this)).ServiceOperation(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GeneratorService.JavaServer.ServiceOperationResponse1> GeneratorService.JavaServer.Generator.ServiceOperationAsync(GeneratorService.JavaServer.ServiceOperationRequest request) {
            return base.Channel.ServiceOperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<GeneratorService.JavaServer.ServiceOperationResponse1> ServiceOperationAsync(string apptoken, object[] data, string info, int operations, int status, string usertoken) {
            GeneratorService.JavaServer.ServiceOperationRequest inValue = new GeneratorService.JavaServer.ServiceOperationRequest();
            inValue.apptoken = apptoken;
            inValue.data = data;
            inValue.info = info;
            inValue.operations = operations;
            inValue.status = status;
            inValue.usertoken = usertoken;
            return ((GeneratorService.JavaServer.Generator)(this)).ServiceOperationAsync(inValue);
        }
    }
}
